version: '3.8'

services:
  elasticsearch:
    image: duongshiro/elasticsearch:5.6
    container_name: elasticsearch-cfn
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - default
    restart: unless-stopped

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:6.8.23
  #   container_name: kibana
  #   hostname: kibana
  #   ports:
  #     - "5601:5601"
  #   networks:
  #   - default

networks:
  default:

# docker-compose up
